// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"google.golang.org/grpc"
	"pixstall-user/app/auth/delivery/http"
	grpc2 "pixstall-user/app/auth/repository/grpc"
	"pixstall-user/app/auth/usecase"
	"pixstall-user/app/user/repository/mongo"
)

// Injectors from wire.go:

func InitAuthController(grpcConn *grpc.ClientConn) http.AuthController {
	repo := grpc2.NewGRPCAuthRepository(grpcConn)
	userRepo := mongo.NewMongoUserRepo()
	useCase := usecase.NewAuthUseCase(repo, userRepo)
	authController := http.NewAuthController(useCase)
	return authController
}
